site_name: GophKeeper Authenticator
site_description: Клиент-серверный менеджер секретов с клиентским шифрованием vault.
repo_url: https://github.com/squaredbusinessman/GophKeeper-Authenticator
theme:
  name: mkdocs
nav:
  - Обзор: index.md
  - Клиент: client.md
  - Сервер: server.md
  - API: api.md
  - Развертывание: deployment.md
